apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  selector:
    matchLabels:
      deployment: node
  template:
    metadata:
      labels:
        deployment: node
    spec:
      containers:
      - image: nodejs:10
        name: node
        env:
        - name: MIO
          value: "Marce"
